version: '3.7'

services:
  proxy_service:
    image: nginx:latest
    container_name: proxy_service
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped
    networks:
      - proxy_network
  server:
    build:
      context: ./
      target: development-build-stage
      dockerfile: Dockerfile
    container_name: server_service
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - proxy_network
    links:
      - postgres
    depands_on:
      - postgres
  postgres:
    image: postgres:latest
    container_name: postgres_service
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - proxy_network

networks:
  proxy_network:
    driver: bridge

volumes:
  data:
    driver: local
